name: 'Spectro Cloud Kubernetes'
description: 'Set Kubernetes kubeconfig context for Spectro Cloud Kubernetes (K8s) Platform as a Service clusters'
author: 'Spectro Cloud'
inputs:
  host:
    required: false
    description: Spectro Cloud API Endpoint
    default: api.spectrocloud.com
  username:
    required: true
    description: Spectro Cloud API Username
  password:
    required: true
    description: Spectro Cloud API Username
  projectName:
    required: true
    description: Spectro Cloud Project Name
  clusterName:
    required: false
    description: Spectro Cloud Cluster Name
  clusterTags:
    required: false
    description: Spectro Cloud Cluster Tags
branding:
  color: 'purple'
  icon: 'anchor'
runs:
  using: 'node12'
  main: 'dist/index.js'
