name: 'Spectro Cloud K8s set context'
description: 'Set Kubeconfig for Spectro Cloud K8s clusters'
author: 'Spectro Cloud'
inputs:
  host:
    required: true
    description: Spectro Cloud API Endpoint
    default: api.spectrocloud.com
  username:
    required: true
    description: Spectro Cloud API Username
  password:
    required: true
    description: Spectro Cloud API Username
  projectName:
    required: true
    description: Spectro Cloud Project Name
  clusterName:
    required: true
    description: Spectro Cloud Cluster Name
branding:
  color: 'blue'
  icon: 'arrow-down-circle'
runs:
  using: 'node12'
  main: 'dist/index.js'
